export const CLASS_ACTIVE = 'is-active'
export const CLASS_CHANGING = 'is-changing'
export const CLASS_FULLY_SCROLLED = 'is-fully-scrolled'
export const CLASS_PRINT_ONLY = 'footnote-print-only'
export const CLASS_SCROLLABLE = 'is-scrollable'

export const CLASS_HOST = 'littlefoot-footnote__host'
export const CLASS_CONTENT = 'littlefoot-footnote__content'
export const CLASS_TOOLTIP = 'littlefoot-footnote__tooltip'
export const CLASS_WRAPPER = 'littlefoot-footnote__wrapper'

export const DATA_BUTTON = 'data-footnote-button'
export const DATA_POPOVER = 'data-footnote-popover'
export const DATA_ID = 'data-footnote-id'
export const DATA_POPOVER_POSITION = 'data-footnote-position'
