export const CLASS_ACTIVE = 'is-active'
export const CLASS_CHANGING = 'is-changing'
export const CLASS_FULLY_SCROLLED = 'is-fully-scrolled'
export const CLASS_HOVERED = 'is-hovered'
export const CLASS_SCROLLABLE = 'is-scrollable'

export const CLASS_BUTTON = 'littlefoot-footnote__button'
export const CLASS_CONTENT = 'littlefoot-footnote__content'
export const CLASS_FOOTNOTE = 'littlefoot-footnote'
export const CLASS_TOOLTIP = 'littlefoot-footnote__tooltip'
export const CLASS_WRAPPER = 'littlefoot-footnote__wrapper'

export const CLASS_PRINT_ONLY = 'footnote-print-only'
export const CLASS_PROCESSED = 'footnote-processed'

export const FOOTNOTE_BACKLINK_REF = 'data-footnote-backlink-ref'
export const FOOTNOTE_CONTENT = 'data-footnote-content'
export const FOOTNOTE_ID = 'data-footnote-id'
export const FOOTNOTE_MAX_HEIGHT = 'data-footnote-max-height'
export const FOOTNOTE_NUMBER = 'data-footnote-number'
export const FOOTNOTE_REF = 'data-footnote-ref'
export const FOOTNOTE_STATE = 'data-footnote-state'
